### ISSUE TITLE
Using ioctl to calculate available sectors instead of sysfs

### ISSUE THREAD

**Issue by cqs21** [jinzhao-dev/jinzhao-disk#23]
Note that the capacity of a JinDisk logical block device must be less than that of the underlying untrusted block device. This is because some storage space of the untrusted block device is consumed by JinDisk to store metadata, instead of user data. 

Hence, JinDisk provides a sysfs interface to calculate the maximum capacity of a JinDisk instance that may be created on the untrusted block device.
```bash
$ sudo echo <untrusted_dev_sectors> > /sys/module/jindisk/calc_avail_sectors
$ sudo cat /sys/module/jindisk/calc_avail_sectors
```
However, this function is only needed by the `jindisksetup` tool, not all normal users. In addition, race condition may also yield incorrect result.

**Comment by StanPlatinum** [comment]
PR https://github.com/jinzhao-dev/jinzhao-disk/pull/24 and PR https://github.com/jinzhao-dev/jinzhao-disk/pull/33 have fixed this issue.
